### ISSUE TITLE
Risk Treatment Options Integration

### ISSUE THREAD

**Issue by seb-kw** [l3montree-dev/flawfix#35]
As a user, I want to mitigate my risks in FlawFix according to the following schema:

- **Accept:** Justify the action without identifying a risk responsible.

- **Mitigate:** Integrate with a ticket system to create a ticket with all necessary information and assign a responsible person for its resolution.

- **Transfer:** Send an email with ticket information to a responsible party and track the recipient in FlawFix. Responses to the email should automatically create a comment in FlawFix for seamless communication across different media.

- **Avoid:** Require justification for the 'Avoid' mitigation type.

**Comment by timbastin** [comment]
Is in development: https://github.com/l3montree-dev/flawfix/pull/91
