### ISSUE TITLE
API Documentation needed 

### ISSUE THREAD

**Issue by seb-kw** [l3montree-dev/flawfix#82]
Related to: #78 

Requirement (currently marked as unmet): 
> The project MUST provide reference documentation that describes the external interface (both input and output) of the software produced by the project.

I suggest we provide a documentation based on an OpenAPI spec.

**Comment by Liamhhhhh** [comment]
Documents based on the OpenAPI specification can be automatically generated using [Apidog](https://www.apidog.com/?utm_source=&utm_medium=blogger&utm_campaign=test1), and I think the UI looks great. Just a small suggestion from my experience. 
﻿ 
﻿

**Comment by seb-kw** [comment]
Thank you, @Liamhhhhh, for your input — much appreciated! Simplification and automation are (almost) always a good thing 😃 -  we'll take a look at it!

Do you know of any comparable alternatives from your experience? We try to rely exclusively on other open-source projects — after a quick look at Apidog, it looked more like closed source (but please don't hesitate to correct me here).

**Comment by arne-kroeger** [comment]
Hi @seb-kw,

why not using Swaggo (Swagger for Go) to generate the documentation automatically during pipeline and provide the up-2-date version directly for external clients?

**Comment by seb-kw** [comment]
Thanks @arne-kroeger ! 

Looks like a cool option - we'll give it a try here: #94
